packages:
  - packages/*
  - apps/*
  - demo/*

catalog:
  '@tonconnect/sdk': 3.3.1
  '@tonconnect/ui-react': 2.3.1
  '@tonconnect/protocol': 2.3.0
  '@types/react': 19.2.8
  '@types/react-dom': 19.2.3
  react: 19.2.3
  react-dom: 19.2.3
  react-native: 0.81.5

onlyBuiltDependencies:
  - node-hid
