packages:
  - packages/*
  - apps/*
  - demo/*

catalog:
  '@tanstack/query-core': 5.90.20
  '@tanstack/react-query': 5.90.20
  '@ton/core': ^0.63.0
  '@ton/crypto': 3.3.0
  '@tonconnect/sdk': 3.4.1
  '@tonconnect/ui': 2.4.1
  '@tonconnect/ui-react': 2.4.1
  '@tonconnect/protocol': 2.4.0
  '@types/react': 19.2.8
  '@types/react-dom': 19.2.3
  react: 19.2.3
  react-dom: 19.2.3
  react-native: 0.81.5

onlyBuiltDependencies:
  - node-hid

catalogs:
  react-native:
    react: 19.1.0
    react-dom: 19.1.0
    react-native: 0.81.5
    '@types/react': 19.1.17
    '@types/react-dom': 19.1.0
