packages:
  - packages/*
  - apps/*
  - demo/*

onlyBuiltDependencies:
  - node-hid

catalog:
  react: 19.1.0
  react-native: 0.81.5
  react-dom: 19.1.0
  '@types/react': 19.1.17
  '@types/react-dom': 19.1.7
